version: 2.1

jobs:
  checkoutEtTests:
    machine: true
    steps:
      - run: git clone https://github.com/vinbail/3w5-h24-tp2-backend.git
      - run: cd /3w5-h24-tp2-backend
      - run: ls -a
  # integrationFrontend:
  #   machine: true
  #   steps:
  #     - run: echo "second job, first step"
  #     - run: echo "second job, second step"
  # deploiement:
  #   machine: true
  #   steps:
  #     - run: echo "Continuing from job 1 and 2, to job 3"

workflows:
  build:
    jobs:
      - job1
      - job2
      - job3:
          requires:
            - job1
            - job2
      - job4
      - job5
      - job6:
          requires:
            - job3
            - job4
            - job5